CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250831150255_InitialCreate') THEN
    CREATE TABLE "Drivers" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "FirstName" text NOT NULL,
        "LastName" text NOT NULL,
        "CountryAbbreviation" text,
        "DateOfBirth" timestamp with time zone NOT NULL,
        "Number" integer,
        "Price" numeric NOT NULL,
        "Points" integer NOT NULL,
        CONSTRAINT "PK_Drivers" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250831150255_InitialCreate') THEN
    CREATE TABLE "Teams" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Name" text NOT NULL,
        "OwnerName" text NOT NULL,
        "TotalPoints" integer NOT NULL,
        CONSTRAINT "PK_Teams" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250831150255_InitialCreate') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20250831150255_InitialCreate', '9.0.8');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250901172103_AddRankToTeam') THEN
    ALTER TABLE "Teams" ADD "Rank" integer NOT NULL DEFAULT 0;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250901172103_AddRankToTeam') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20250901172103_AddRankToTeam', '9.0.8');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250906220309_AddUserProfile') THEN
    CREATE TABLE "Accounts" (
        "Id" character varying(36) NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone NOT NULL,
        "IsActive" boolean NOT NULL,
        "LastLoginAt" timestamp with time zone,
        CONSTRAINT "PK_Accounts" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250906220309_AddUserProfile') THEN
    CREATE TABLE "UserProfiles" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "AccountId" character varying(36) NOT NULL,
        "DisplayName" text,
        "Email" text NOT NULL,
        "FirstName" text,
        "LastName" text,
        "AvatarUrl" text,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_UserProfiles" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_UserProfiles_Accounts_AccountId" FOREIGN KEY ("AccountId") REFERENCES "Accounts" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250906220309_AddUserProfile') THEN
    CREATE UNIQUE INDEX "IX_UserProfiles_AccountId" ON "UserProfiles" ("AccountId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250906220309_AddUserProfile') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20250906220309_AddUserProfile', '9.0.8');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250906235800_AddUniqueEmailIndex') THEN
    CREATE UNIQUE INDEX "IX_UserProfiles_Email" ON "UserProfiles" ("Email");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250906235800_AddUniqueEmailIndex') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20250906235800_AddUniqueEmailIndex', '9.0.8');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250930130828_AddLeague') THEN
    CREATE TABLE "Leagues" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Name" text NOT NULL,
        "OwnerId" integer NOT NULL,
        CONSTRAINT "PK_Leagues" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Leagues_UserProfiles_OwnerId" FOREIGN KEY ("OwnerId") REFERENCES "UserProfiles" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250930130828_AddLeague') THEN
    CREATE INDEX "IX_Leagues_OwnerId" ON "Leagues" ("OwnerId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250930130828_AddLeague') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20250930130828_AddLeague', '9.0.8');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251005234437_AddLeagueProperties') THEN
    ALTER TABLE "UserProfiles" ADD "CreatedBy" integer NOT NULL DEFAULT 0;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251005234437_AddLeagueProperties') THEN
    ALTER TABLE "UserProfiles" ADD "DeletedAt" timestamp with time zone NOT NULL DEFAULT TIMESTAMPTZ '-infinity';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251005234437_AddLeagueProperties') THEN
    ALTER TABLE "UserProfiles" ADD "DeletedBy" integer NOT NULL DEFAULT 0;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251005234437_AddLeagueProperties') THEN
    ALTER TABLE "UserProfiles" ADD "IsDeleted" boolean NOT NULL DEFAULT FALSE;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251005234437_AddLeagueProperties') THEN
    ALTER TABLE "UserProfiles" ADD "UpdatedBy" integer NOT NULL DEFAULT 0;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251005234437_AddLeagueProperties') THEN
    ALTER TABLE "Teams" ADD "CreatedAt" timestamp with time zone NOT NULL DEFAULT TIMESTAMPTZ '-infinity';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251005234437_AddLeagueProperties') THEN
    ALTER TABLE "Teams" ADD "CreatedBy" integer NOT NULL DEFAULT 0;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251005234437_AddLeagueProperties') THEN
    ALTER TABLE "Teams" ADD "DeletedAt" timestamp with time zone NOT NULL DEFAULT TIMESTAMPTZ '-infinity';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251005234437_AddLeagueProperties') THEN
    ALTER TABLE "Teams" ADD "DeletedBy" integer NOT NULL DEFAULT 0;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251005234437_AddLeagueProperties') THEN
    ALTER TABLE "Teams" ADD "IsDeleted" boolean NOT NULL DEFAULT FALSE;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251005234437_AddLeagueProperties') THEN
    ALTER TABLE "Teams" ADD "UpdatedAt" timestamp with time zone NOT NULL DEFAULT TIMESTAMPTZ '-infinity';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251005234437_AddLeagueProperties') THEN
    ALTER TABLE "Teams" ADD "UpdatedBy" integer NOT NULL DEFAULT 0;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251005234437_AddLeagueProperties') THEN
    ALTER TABLE "Leagues" ADD "CreatedAt" timestamp with time zone NOT NULL DEFAULT TIMESTAMPTZ '-infinity';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251005234437_AddLeagueProperties') THEN
    ALTER TABLE "Leagues" ADD "CreatedBy" integer NOT NULL DEFAULT 0;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251005234437_AddLeagueProperties') THEN
    ALTER TABLE "Leagues" ADD "DeletedAt" timestamp with time zone NOT NULL DEFAULT TIMESTAMPTZ '-infinity';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251005234437_AddLeagueProperties') THEN
    ALTER TABLE "Leagues" ADD "DeletedBy" integer NOT NULL DEFAULT 0;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251005234437_AddLeagueProperties') THEN
    ALTER TABLE "Leagues" ADD "IsDeleted" boolean NOT NULL DEFAULT FALSE;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251005234437_AddLeagueProperties') THEN
    ALTER TABLE "Leagues" ADD "UpdatedAt" timestamp with time zone NOT NULL DEFAULT TIMESTAMPTZ '-infinity';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251005234437_AddLeagueProperties') THEN
    ALTER TABLE "Leagues" ADD "UpdatedBy" integer NOT NULL DEFAULT 0;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251005234437_AddLeagueProperties') THEN
    ALTER TABLE "Drivers" ADD "CreatedAt" timestamp with time zone NOT NULL DEFAULT TIMESTAMPTZ '-infinity';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251005234437_AddLeagueProperties') THEN
    ALTER TABLE "Drivers" ADD "CreatedBy" integer NOT NULL DEFAULT 0;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251005234437_AddLeagueProperties') THEN
    ALTER TABLE "Drivers" ADD "DeletedAt" timestamp with time zone NOT NULL DEFAULT TIMESTAMPTZ '-infinity';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251005234437_AddLeagueProperties') THEN
    ALTER TABLE "Drivers" ADD "DeletedBy" integer NOT NULL DEFAULT 0;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251005234437_AddLeagueProperties') THEN
    ALTER TABLE "Drivers" ADD "IsDeleted" boolean NOT NULL DEFAULT FALSE;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251005234437_AddLeagueProperties') THEN
    ALTER TABLE "Drivers" ADD "UpdatedAt" timestamp with time zone NOT NULL DEFAULT TIMESTAMPTZ '-infinity';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251005234437_AddLeagueProperties') THEN
    ALTER TABLE "Drivers" ADD "UpdatedBy" integer NOT NULL DEFAULT 0;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251005234437_AddLeagueProperties') THEN
    ALTER TABLE "Accounts" ADD "CreatedBy" integer NOT NULL DEFAULT 0;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251005234437_AddLeagueProperties') THEN
    ALTER TABLE "Accounts" ADD "DeletedAt" timestamp with time zone NOT NULL DEFAULT TIMESTAMPTZ '-infinity';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251005234437_AddLeagueProperties') THEN
    ALTER TABLE "Accounts" ADD "DeletedBy" integer NOT NULL DEFAULT 0;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251005234437_AddLeagueProperties') THEN
    ALTER TABLE "Accounts" ADD "IsDeleted" boolean NOT NULL DEFAULT FALSE;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251005234437_AddLeagueProperties') THEN
    ALTER TABLE "Accounts" ADD "UpdatedBy" integer NOT NULL DEFAULT 0;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251005234437_AddLeagueProperties') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20251005234437_AddLeagueProperties', '9.0.8');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251005234839_MakeBaseUDFieldsNullable') THEN
    ALTER TABLE "UserProfiles" ALTER COLUMN "UpdatedBy" DROP NOT NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251005234839_MakeBaseUDFieldsNullable') THEN
    ALTER TABLE "UserProfiles" ALTER COLUMN "UpdatedAt" DROP NOT NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251005234839_MakeBaseUDFieldsNullable') THEN
    ALTER TABLE "UserProfiles" ALTER COLUMN "DeletedBy" DROP NOT NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251005234839_MakeBaseUDFieldsNullable') THEN
    ALTER TABLE "UserProfiles" ALTER COLUMN "DeletedAt" DROP NOT NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251005234839_MakeBaseUDFieldsNullable') THEN
    ALTER TABLE "Teams" ALTER COLUMN "UpdatedBy" DROP NOT NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251005234839_MakeBaseUDFieldsNullable') THEN
    ALTER TABLE "Teams" ALTER COLUMN "UpdatedAt" DROP NOT NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251005234839_MakeBaseUDFieldsNullable') THEN
    ALTER TABLE "Teams" ALTER COLUMN "DeletedBy" DROP NOT NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251005234839_MakeBaseUDFieldsNullable') THEN
    ALTER TABLE "Teams" ALTER COLUMN "DeletedAt" DROP NOT NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251005234839_MakeBaseUDFieldsNullable') THEN
    ALTER TABLE "Leagues" ALTER COLUMN "UpdatedBy" DROP NOT NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251005234839_MakeBaseUDFieldsNullable') THEN
    ALTER TABLE "Leagues" ALTER COLUMN "UpdatedAt" DROP NOT NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251005234839_MakeBaseUDFieldsNullable') THEN
    ALTER TABLE "Leagues" ALTER COLUMN "DeletedBy" DROP NOT NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251005234839_MakeBaseUDFieldsNullable') THEN
    ALTER TABLE "Leagues" ALTER COLUMN "DeletedAt" DROP NOT NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251005234839_MakeBaseUDFieldsNullable') THEN
    ALTER TABLE "Drivers" ALTER COLUMN "UpdatedBy" DROP NOT NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251005234839_MakeBaseUDFieldsNullable') THEN
    ALTER TABLE "Drivers" ALTER COLUMN "UpdatedAt" DROP NOT NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251005234839_MakeBaseUDFieldsNullable') THEN
    ALTER TABLE "Drivers" ALTER COLUMN "DeletedBy" DROP NOT NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251005234839_MakeBaseUDFieldsNullable') THEN
    ALTER TABLE "Drivers" ALTER COLUMN "DeletedAt" DROP NOT NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251005234839_MakeBaseUDFieldsNullable') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20251005234839_MakeBaseUDFieldsNullable', '9.0.8');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251006125623_EnhanceLeagueWithMoreDescMaxTeamsAndIsPrivate') THEN
    ALTER TABLE "Leagues" ADD "Description" text NOT NULL DEFAULT '';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251006125623_EnhanceLeagueWithMoreDescMaxTeamsAndIsPrivate') THEN
    ALTER TABLE "Leagues" ADD "IsPrivate" boolean NOT NULL DEFAULT FALSE;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251006125623_EnhanceLeagueWithMoreDescMaxTeamsAndIsPrivate') THEN
    ALTER TABLE "Leagues" ADD "MaxTeams" text NOT NULL DEFAULT '';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251006125623_EnhanceLeagueWithMoreDescMaxTeamsAndIsPrivate') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20251006125623_EnhanceLeagueWithMoreDescMaxTeamsAndIsPrivate', '9.0.8');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251007130051_FixMaxTeamsToBoolean') THEN
    ALTER TABLE "Leagues" ADD "MaxTeams_temp" boolean NOT NULL DEFAULT FALSE;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251007130051_FixMaxTeamsToBoolean') THEN

                    UPDATE "Leagues" 
                    SET "MaxTeams_temp" = CASE 
                        WHEN LOWER("MaxTeams") IN ('true', 't', 'yes', 'y', '1') THEN true
                        ELSE false 
                    END;
                
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251007130051_FixMaxTeamsToBoolean') THEN
    ALTER TABLE "Leagues" DROP COLUMN "MaxTeams";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251007130051_FixMaxTeamsToBoolean') THEN
    ALTER TABLE "Leagues" RENAME COLUMN "MaxTeams_temp" TO "MaxTeams";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251007130051_FixMaxTeamsToBoolean') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20251007130051_FixMaxTeamsToBoolean', '9.0.8');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251011013549_AddAuditTrailForeignKeys') THEN
    CREATE INDEX "IX_UserProfiles_CreatedBy" ON "UserProfiles" ("CreatedBy");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251011013549_AddAuditTrailForeignKeys') THEN
    CREATE INDEX "IX_UserProfiles_DeletedBy" ON "UserProfiles" ("DeletedBy");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251011013549_AddAuditTrailForeignKeys') THEN
    CREATE INDEX "IX_UserProfiles_UpdatedBy" ON "UserProfiles" ("UpdatedBy");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251011013549_AddAuditTrailForeignKeys') THEN
    CREATE INDEX "IX_Teams_CreatedBy" ON "Teams" ("CreatedBy");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251011013549_AddAuditTrailForeignKeys') THEN
    CREATE INDEX "IX_Teams_DeletedBy" ON "Teams" ("DeletedBy");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251011013549_AddAuditTrailForeignKeys') THEN
    CREATE INDEX "IX_Teams_UpdatedBy" ON "Teams" ("UpdatedBy");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251011013549_AddAuditTrailForeignKeys') THEN
    CREATE INDEX "IX_Leagues_CreatedBy" ON "Leagues" ("CreatedBy");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251011013549_AddAuditTrailForeignKeys') THEN
    CREATE INDEX "IX_Leagues_DeletedBy" ON "Leagues" ("DeletedBy");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251011013549_AddAuditTrailForeignKeys') THEN
    CREATE INDEX "IX_Leagues_UpdatedBy" ON "Leagues" ("UpdatedBy");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251011013549_AddAuditTrailForeignKeys') THEN
    CREATE INDEX "IX_Drivers_CreatedBy" ON "Drivers" ("CreatedBy");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251011013549_AddAuditTrailForeignKeys') THEN
    CREATE INDEX "IX_Drivers_DeletedBy" ON "Drivers" ("DeletedBy");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251011013549_AddAuditTrailForeignKeys') THEN
    CREATE INDEX "IX_Drivers_UpdatedBy" ON "Drivers" ("UpdatedBy");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251011013549_AddAuditTrailForeignKeys') THEN
    ALTER TABLE "Drivers" ADD CONSTRAINT "FK_Drivers_UserProfiles_CreatedBy" FOREIGN KEY ("CreatedBy") REFERENCES "UserProfiles" ("Id") ON DELETE RESTRICT;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251011013549_AddAuditTrailForeignKeys') THEN
    ALTER TABLE "Drivers" ADD CONSTRAINT "FK_Drivers_UserProfiles_DeletedBy" FOREIGN KEY ("DeletedBy") REFERENCES "UserProfiles" ("Id") ON DELETE RESTRICT;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251011013549_AddAuditTrailForeignKeys') THEN
    ALTER TABLE "Drivers" ADD CONSTRAINT "FK_Drivers_UserProfiles_UpdatedBy" FOREIGN KEY ("UpdatedBy") REFERENCES "UserProfiles" ("Id") ON DELETE RESTRICT;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251011013549_AddAuditTrailForeignKeys') THEN
    ALTER TABLE "Leagues" ADD CONSTRAINT "FK_Leagues_UserProfiles_CreatedBy" FOREIGN KEY ("CreatedBy") REFERENCES "UserProfiles" ("Id") ON DELETE RESTRICT;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251011013549_AddAuditTrailForeignKeys') THEN
    ALTER TABLE "Leagues" ADD CONSTRAINT "FK_Leagues_UserProfiles_DeletedBy" FOREIGN KEY ("DeletedBy") REFERENCES "UserProfiles" ("Id") ON DELETE RESTRICT;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251011013549_AddAuditTrailForeignKeys') THEN
    ALTER TABLE "Leagues" ADD CONSTRAINT "FK_Leagues_UserProfiles_UpdatedBy" FOREIGN KEY ("UpdatedBy") REFERENCES "UserProfiles" ("Id") ON DELETE RESTRICT;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251011013549_AddAuditTrailForeignKeys') THEN
    ALTER TABLE "Teams" ADD CONSTRAINT "FK_Teams_UserProfiles_CreatedBy" FOREIGN KEY ("CreatedBy") REFERENCES "UserProfiles" ("Id") ON DELETE RESTRICT;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251011013549_AddAuditTrailForeignKeys') THEN
    ALTER TABLE "Teams" ADD CONSTRAINT "FK_Teams_UserProfiles_DeletedBy" FOREIGN KEY ("DeletedBy") REFERENCES "UserProfiles" ("Id") ON DELETE RESTRICT;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251011013549_AddAuditTrailForeignKeys') THEN
    ALTER TABLE "Teams" ADD CONSTRAINT "FK_Teams_UserProfiles_UpdatedBy" FOREIGN KEY ("UpdatedBy") REFERENCES "UserProfiles" ("Id") ON DELETE RESTRICT;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251011013549_AddAuditTrailForeignKeys') THEN
    ALTER TABLE "UserProfiles" ADD CONSTRAINT "FK_UserProfiles_UserProfiles_CreatedBy" FOREIGN KEY ("CreatedBy") REFERENCES "UserProfiles" ("Id") ON DELETE RESTRICT;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251011013549_AddAuditTrailForeignKeys') THEN
    ALTER TABLE "UserProfiles" ADD CONSTRAINT "FK_UserProfiles_UserProfiles_DeletedBy" FOREIGN KEY ("DeletedBy") REFERENCES "UserProfiles" ("Id") ON DELETE RESTRICT;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251011013549_AddAuditTrailForeignKeys') THEN
    ALTER TABLE "UserProfiles" ADD CONSTRAINT "FK_UserProfiles_UserProfiles_UpdatedBy" FOREIGN KEY ("UpdatedBy") REFERENCES "UserProfiles" ("Id") ON DELETE RESTRICT;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251011013549_AddAuditTrailForeignKeys') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20251011013549_AddAuditTrailForeignKeys', '9.0.8');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251011234744_RemoveCreatedDeletedUpdatedByFromAccount') THEN
    ALTER TABLE "Accounts" DROP COLUMN "CreatedBy";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251011234744_RemoveCreatedDeletedUpdatedByFromAccount') THEN
    ALTER TABLE "Accounts" DROP COLUMN "DeletedBy";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251011234744_RemoveCreatedDeletedUpdatedByFromAccount') THEN
    ALTER TABLE "Accounts" DROP COLUMN "UpdatedBy";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251011234744_RemoveCreatedDeletedUpdatedByFromAccount') THEN
    ALTER TABLE "Accounts" ALTER COLUMN "DeletedAt" DROP NOT NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251011234744_RemoveCreatedDeletedUpdatedByFromAccount') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20251011234744_RemoveCreatedDeletedUpdatedByFromAccount', '9.0.8');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251012233027_RemoveBaseEntityFromUserProfile') THEN
    ALTER TABLE "UserProfiles" DROP CONSTRAINT "FK_UserProfiles_UserProfiles_CreatedBy";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251012233027_RemoveBaseEntityFromUserProfile') THEN
    ALTER TABLE "UserProfiles" DROP CONSTRAINT "FK_UserProfiles_UserProfiles_DeletedBy";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251012233027_RemoveBaseEntityFromUserProfile') THEN
    ALTER TABLE "UserProfiles" DROP CONSTRAINT "FK_UserProfiles_UserProfiles_UpdatedBy";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251012233027_RemoveBaseEntityFromUserProfile') THEN
    DROP INDEX "IX_UserProfiles_CreatedBy";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251012233027_RemoveBaseEntityFromUserProfile') THEN
    DROP INDEX "IX_UserProfiles_DeletedBy";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251012233027_RemoveBaseEntityFromUserProfile') THEN
    DROP INDEX "IX_UserProfiles_UpdatedBy";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251012233027_RemoveBaseEntityFromUserProfile') THEN
    ALTER TABLE "UserProfiles" DROP COLUMN "CreatedAt";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251012233027_RemoveBaseEntityFromUserProfile') THEN
    ALTER TABLE "UserProfiles" DROP COLUMN "CreatedBy";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251012233027_RemoveBaseEntityFromUserProfile') THEN
    ALTER TABLE "UserProfiles" DROP COLUMN "DeletedAt";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251012233027_RemoveBaseEntityFromUserProfile') THEN
    ALTER TABLE "UserProfiles" DROP COLUMN "DeletedBy";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251012233027_RemoveBaseEntityFromUserProfile') THEN
    ALTER TABLE "UserProfiles" DROP COLUMN "IsDeleted";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251012233027_RemoveBaseEntityFromUserProfile') THEN
    ALTER TABLE "UserProfiles" DROP COLUMN "UpdatedAt";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251012233027_RemoveBaseEntityFromUserProfile') THEN
    ALTER TABLE "UserProfiles" DROP COLUMN "UpdatedBy";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251012233027_RemoveBaseEntityFromUserProfile') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20251012233027_RemoveBaseEntityFromUserProfile', '9.0.8');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251013003634_UpdateLeagueMaxTeamsToBeIntFromBoolean') THEN
    ALTER TABLE "Leagues" 
              ALTER COLUMN "MaxTeams" DROP DEFAULT;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251013003634_UpdateLeagueMaxTeamsToBeIntFromBoolean') THEN
    ALTER TABLE "Leagues" 
              ALTER COLUMN "MaxTeams" TYPE integer 
              USING (CASE WHEN "MaxTeams" = true THEN 1 ELSE 0 END);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251013003634_UpdateLeagueMaxTeamsToBeIntFromBoolean') THEN
    ALTER TABLE "Leagues" 
              ALTER COLUMN "MaxTeams" SET DEFAULT 0;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251013003634_UpdateLeagueMaxTeamsToBeIntFromBoolean') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20251013003634_UpdateLeagueMaxTeamsToBeIntFromBoolean', '9.0.8');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251021185733_MakeAuditTrailFieldsOptional') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20251021185733_MakeAuditTrailFieldsOptional', '9.0.8');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251021191028_RemoveDefaultValuesFromNullableAuditFields') THEN
    ALTER TABLE "Drivers" ALTER COLUMN "UpdatedBy" DROP DEFAULT;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251021191028_RemoveDefaultValuesFromNullableAuditFields') THEN
    ALTER TABLE "Drivers" ALTER COLUMN "DeletedBy" DROP DEFAULT;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251021191028_RemoveDefaultValuesFromNullableAuditFields') THEN
    ALTER TABLE "Leagues" ALTER COLUMN "UpdatedBy" DROP DEFAULT;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251021191028_RemoveDefaultValuesFromNullableAuditFields') THEN
    ALTER TABLE "Leagues" ALTER COLUMN "DeletedBy" DROP DEFAULT;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251021191028_RemoveDefaultValuesFromNullableAuditFields') THEN
    ALTER TABLE "Teams" ALTER COLUMN "UpdatedBy" DROP DEFAULT;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251021191028_RemoveDefaultValuesFromNullableAuditFields') THEN
    ALTER TABLE "Teams" ALTER COLUMN "DeletedBy" DROP DEFAULT;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251021191028_RemoveDefaultValuesFromNullableAuditFields') THEN

                    UPDATE "Drivers" SET "DeletedBy" = NULL WHERE "DeletedBy" = 0;
                    UPDATE "Drivers" SET "UpdatedBy" = NULL WHERE "UpdatedBy" = 0;
                    UPDATE "Leagues" SET "DeletedBy" = NULL WHERE "DeletedBy" = 0;
                    UPDATE "Leagues" SET "UpdatedBy" = NULL WHERE "UpdatedBy" = 0;
                    UPDATE "Teams" SET "DeletedBy" = NULL WHERE "DeletedBy" = 0;
                    UPDATE "Teams" SET "UpdatedBy" = NULL WHERE "UpdatedBy" = 0;
                
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251021191028_RemoveDefaultValuesFromNullableAuditFields') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20251021191028_RemoveDefaultValuesFromNullableAuditFields', '9.0.8');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251024041422_LeagueMakeDescriptionNullableAndSetDefaultsForMaxTeamsAndIsPrivate') THEN
    ALTER TABLE "Leagues" ALTER COLUMN "Description" DROP NOT NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251024041422_LeagueMakeDescriptionNullableAndSetDefaultsForMaxTeamsAndIsPrivate') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20251024041422_LeagueMakeDescriptionNullableAndSetDefaultsForMaxTeamsAndIsPrivate', '9.0.8');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251113014706_AddUserTeamRelationship') THEN
    ALTER TABLE "Teams" ADD "UserId" integer NOT NULL DEFAULT 0;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251113014706_AddUserTeamRelationship') THEN
    CREATE UNIQUE INDEX "IX_Teams_UserId" ON "Teams" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251113014706_AddUserTeamRelationship') THEN
    ALTER TABLE "Teams" ADD CONSTRAINT "FK_Teams_UserProfiles_UserId" FOREIGN KEY ("UserId") REFERENCES "UserProfiles" ("Id") ON DELETE RESTRICT;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251113014706_AddUserTeamRelationship') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20251113014706_AddUserTeamRelationship', '9.0.8');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251113020219_EnsureOneToOneUserTeamRelationshipIsUnique') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20251113020219_EnsureOneToOneUserTeamRelationshipIsUnique', '9.0.8');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251113041721_RemoveRankOwnerNameTotalPointsFromTeam') THEN
    ALTER TABLE "Teams" DROP COLUMN "OwnerName";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251113041721_RemoveRankOwnerNameTotalPointsFromTeam') THEN
    ALTER TABLE "Teams" DROP COLUMN "Rank";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251113041721_RemoveRankOwnerNameTotalPointsFromTeam') THEN
    ALTER TABLE "Teams" DROP COLUMN "TotalPoints";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251113041721_RemoveRankOwnerNameTotalPointsFromTeam') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20251113041721_RemoveRankOwnerNameTotalPointsFromTeam', '9.0.8');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251124140336_AddDriverAndConstructor') THEN
    ALTER TABLE "Drivers" DROP COLUMN "Number";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251124140336_AddDriverAndConstructor') THEN
    ALTER TABLE "Drivers" DROP COLUMN "Points";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251124140336_AddDriverAndConstructor') THEN
    ALTER TABLE "Drivers" DROP COLUMN "Price";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251124140336_AddDriverAndConstructor') THEN
    UPDATE "Drivers" SET "CountryAbbreviation" = '' WHERE "CountryAbbreviation" IS NULL;
    ALTER TABLE "Drivers" ALTER COLUMN "CountryAbbreviation" SET NOT NULL;
    ALTER TABLE "Drivers" ALTER COLUMN "CountryAbbreviation" SET DEFAULT '';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251124140336_AddDriverAndConstructor') THEN
    ALTER TABLE "Drivers" ADD "Abbreviation" text NOT NULL DEFAULT '';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251124140336_AddDriverAndConstructor') THEN
    ALTER TABLE "Drivers" ADD "IsActive" boolean NOT NULL DEFAULT FALSE;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251124140336_AddDriverAndConstructor') THEN
    CREATE TABLE "Constructors" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Name" text NOT NULL,
        "FullName" text,
        "CountryAbbreviation" text NOT NULL,
        "IsActive" boolean NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "CreatedBy" integer NOT NULL,
        "UpdatedAt" timestamp with time zone,
        "UpdatedBy" integer,
        "DeletedAt" timestamp with time zone,
        "DeletedBy" integer,
        "IsDeleted" boolean NOT NULL,
        CONSTRAINT "PK_Constructors" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Constructors_UserProfiles_CreatedBy" FOREIGN KEY ("CreatedBy") REFERENCES "UserProfiles" ("Id") ON DELETE RESTRICT,
        CONSTRAINT "FK_Constructors_UserProfiles_DeletedBy" FOREIGN KEY ("DeletedBy") REFERENCES "UserProfiles" ("Id") ON DELETE RESTRICT,
        CONSTRAINT "FK_Constructors_UserProfiles_UpdatedBy" FOREIGN KEY ("UpdatedBy") REFERENCES "UserProfiles" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251124140336_AddDriverAndConstructor') THEN
    CREATE INDEX "IX_Constructors_CreatedBy" ON "Constructors" ("CreatedBy");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251124140336_AddDriverAndConstructor') THEN
    CREATE INDEX "IX_Constructors_DeletedBy" ON "Constructors" ("DeletedBy");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251124140336_AddDriverAndConstructor') THEN
    CREATE INDEX "IX_Constructors_UpdatedBy" ON "Constructors" ("UpdatedBy");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251124140336_AddDriverAndConstructor') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20251124140336_AddDriverAndConstructor', '9.0.8');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251126005815_RemoveDateOfBirthFromDriver') THEN
    ALTER TABLE "Drivers" DROP COLUMN "DateOfBirth";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251126005815_RemoveDateOfBirthFromDriver') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20251126005815_RemoveDateOfBirthFromDriver', '9.0.8');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251126030831_SplitBaseEntityIntoUserOwnedEntity') THEN
    ALTER TABLE "Constructors" DROP CONSTRAINT "FK_Constructors_UserProfiles_CreatedBy";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251126030831_SplitBaseEntityIntoUserOwnedEntity') THEN
    ALTER TABLE "Constructors" DROP CONSTRAINT "FK_Constructors_UserProfiles_DeletedBy";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251126030831_SplitBaseEntityIntoUserOwnedEntity') THEN
    ALTER TABLE "Constructors" DROP CONSTRAINT "FK_Constructors_UserProfiles_UpdatedBy";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251126030831_SplitBaseEntityIntoUserOwnedEntity') THEN
    ALTER TABLE "Drivers" DROP CONSTRAINT "FK_Drivers_UserProfiles_CreatedBy";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251126030831_SplitBaseEntityIntoUserOwnedEntity') THEN
    ALTER TABLE "Drivers" DROP CONSTRAINT "FK_Drivers_UserProfiles_DeletedBy";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251126030831_SplitBaseEntityIntoUserOwnedEntity') THEN
    ALTER TABLE "Drivers" DROP CONSTRAINT "FK_Drivers_UserProfiles_UpdatedBy";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251126030831_SplitBaseEntityIntoUserOwnedEntity') THEN
    DROP INDEX "IX_Drivers_CreatedBy";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251126030831_SplitBaseEntityIntoUserOwnedEntity') THEN
    DROP INDEX "IX_Drivers_DeletedBy";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251126030831_SplitBaseEntityIntoUserOwnedEntity') THEN
    DROP INDEX "IX_Drivers_UpdatedBy";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251126030831_SplitBaseEntityIntoUserOwnedEntity') THEN
    DROP INDEX "IX_Constructors_CreatedBy";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251126030831_SplitBaseEntityIntoUserOwnedEntity') THEN
    DROP INDEX "IX_Constructors_DeletedBy";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251126030831_SplitBaseEntityIntoUserOwnedEntity') THEN
    DROP INDEX "IX_Constructors_UpdatedBy";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251126030831_SplitBaseEntityIntoUserOwnedEntity') THEN
    ALTER TABLE "Drivers" DROP COLUMN "CreatedBy";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251126030831_SplitBaseEntityIntoUserOwnedEntity') THEN
    ALTER TABLE "Drivers" DROP COLUMN "DeletedBy";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251126030831_SplitBaseEntityIntoUserOwnedEntity') THEN
    ALTER TABLE "Drivers" DROP COLUMN "UpdatedBy";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251126030831_SplitBaseEntityIntoUserOwnedEntity') THEN
    ALTER TABLE "Constructors" DROP COLUMN "CreatedBy";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251126030831_SplitBaseEntityIntoUserOwnedEntity') THEN
    ALTER TABLE "Constructors" DROP COLUMN "DeletedBy";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251126030831_SplitBaseEntityIntoUserOwnedEntity') THEN
    ALTER TABLE "Constructors" DROP COLUMN "UpdatedBy";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251126030831_SplitBaseEntityIntoUserOwnedEntity') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20251126030831_SplitBaseEntityIntoUserOwnedEntity', '9.0.8');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251126040126_RemoveInfinityDefaultsFromTimestamps') THEN

                    ALTER TABLE "Drivers" ALTER COLUMN "CreatedAt" DROP DEFAULT;
                    ALTER TABLE "Drivers" ALTER COLUMN "UpdatedAt" DROP DEFAULT;
                    ALTER TABLE "Drivers" ALTER COLUMN "DeletedAt" DROP DEFAULT;
                
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251126040126_RemoveInfinityDefaultsFromTimestamps') THEN

                    ALTER TABLE "Constructors" ALTER COLUMN "CreatedAt" DROP DEFAULT;
                    ALTER TABLE "Constructors" ALTER COLUMN "UpdatedAt" DROP DEFAULT;
                    ALTER TABLE "Constructors" ALTER COLUMN "DeletedAt" DROP DEFAULT;
                
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251126040126_RemoveInfinityDefaultsFromTimestamps') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20251126040126_RemoveInfinityDefaultsFromTimestamps', '9.0.8');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251128033740_AddUniqueConstraintsToDriversAndConstructors') THEN
    CREATE UNIQUE INDEX "IX_Drivers_Abbreviation" ON "Drivers" ("Abbreviation");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251128033740_AddUniqueConstraintsToDriversAndConstructors') THEN
    CREATE UNIQUE INDEX "IX_Constructors_Name" ON "Constructors" ("Name");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251128033740_AddUniqueConstraintsToDriversAndConstructors') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20251128033740_AddUniqueConstraintsToDriversAndConstructors', '9.0.8');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251207001544_AddTeamDriverAndConstructorSelections') THEN
    CREATE TABLE "TeamConstructors" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "TeamId" integer NOT NULL,
        "ConstructorId" integer NOT NULL,
        "SlotPosition" integer NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone,
        "DeletedAt" timestamp with time zone,
        "IsDeleted" boolean NOT NULL,
        "CreatedBy" integer NOT NULL,
        "UpdatedBy" integer,
        "DeletedBy" integer,
        CONSTRAINT "PK_TeamConstructors" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_TeamConstructors_Constructors_ConstructorId" FOREIGN KEY ("ConstructorId") REFERENCES "Constructors" ("Id") ON DELETE RESTRICT,
        CONSTRAINT "FK_TeamConstructors_Teams_TeamId" FOREIGN KEY ("TeamId") REFERENCES "Teams" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_TeamConstructors_UserProfiles_CreatedBy" FOREIGN KEY ("CreatedBy") REFERENCES "UserProfiles" ("Id") ON DELETE RESTRICT,
        CONSTRAINT "FK_TeamConstructors_UserProfiles_DeletedBy" FOREIGN KEY ("DeletedBy") REFERENCES "UserProfiles" ("Id") ON DELETE RESTRICT,
        CONSTRAINT "FK_TeamConstructors_UserProfiles_UpdatedBy" FOREIGN KEY ("UpdatedBy") REFERENCES "UserProfiles" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251207001544_AddTeamDriverAndConstructorSelections') THEN
    CREATE TABLE "TeamDrivers" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "TeamId" integer NOT NULL,
        "DriverId" integer NOT NULL,
        "SlotPosition" integer NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone,
        "DeletedAt" timestamp with time zone,
        "IsDeleted" boolean NOT NULL,
        "CreatedBy" integer NOT NULL,
        "UpdatedBy" integer,
        "DeletedBy" integer,
        CONSTRAINT "PK_TeamDrivers" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_TeamDrivers_Drivers_DriverId" FOREIGN KEY ("DriverId") REFERENCES "Drivers" ("Id") ON DELETE RESTRICT,
        CONSTRAINT "FK_TeamDrivers_Teams_TeamId" FOREIGN KEY ("TeamId") REFERENCES "Teams" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_TeamDrivers_UserProfiles_CreatedBy" FOREIGN KEY ("CreatedBy") REFERENCES "UserProfiles" ("Id") ON DELETE RESTRICT,
        CONSTRAINT "FK_TeamDrivers_UserProfiles_DeletedBy" FOREIGN KEY ("DeletedBy") REFERENCES "UserProfiles" ("Id") ON DELETE RESTRICT,
        CONSTRAINT "FK_TeamDrivers_UserProfiles_UpdatedBy" FOREIGN KEY ("UpdatedBy") REFERENCES "UserProfiles" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251207001544_AddTeamDriverAndConstructorSelections') THEN
    CREATE INDEX "IX_TeamConstructors_ConstructorId" ON "TeamConstructors" ("ConstructorId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251207001544_AddTeamDriverAndConstructorSelections') THEN
    CREATE INDEX "IX_TeamConstructors_CreatedBy" ON "TeamConstructors" ("CreatedBy");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251207001544_AddTeamDriverAndConstructorSelections') THEN
    CREATE INDEX "IX_TeamConstructors_DeletedBy" ON "TeamConstructors" ("DeletedBy");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251207001544_AddTeamDriverAndConstructorSelections') THEN
    CREATE UNIQUE INDEX "IX_TeamConstructors_TeamId_ConstructorId" ON "TeamConstructors" ("TeamId", "ConstructorId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251207001544_AddTeamDriverAndConstructorSelections') THEN
    CREATE UNIQUE INDEX "IX_TeamConstructors_TeamId_SlotPosition" ON "TeamConstructors" ("TeamId", "SlotPosition");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251207001544_AddTeamDriverAndConstructorSelections') THEN
    CREATE INDEX "IX_TeamConstructors_UpdatedBy" ON "TeamConstructors" ("UpdatedBy");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251207001544_AddTeamDriverAndConstructorSelections') THEN
    CREATE INDEX "IX_TeamDrivers_CreatedBy" ON "TeamDrivers" ("CreatedBy");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251207001544_AddTeamDriverAndConstructorSelections') THEN
    CREATE INDEX "IX_TeamDrivers_DeletedBy" ON "TeamDrivers" ("DeletedBy");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251207001544_AddTeamDriverAndConstructorSelections') THEN
    CREATE INDEX "IX_TeamDrivers_DriverId" ON "TeamDrivers" ("DriverId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251207001544_AddTeamDriverAndConstructorSelections') THEN
    CREATE UNIQUE INDEX "IX_TeamDrivers_TeamId_DriverId" ON "TeamDrivers" ("TeamId", "DriverId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251207001544_AddTeamDriverAndConstructorSelections') THEN
    CREATE UNIQUE INDEX "IX_TeamDrivers_TeamId_SlotPosition" ON "TeamDrivers" ("TeamId", "SlotPosition");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251207001544_AddTeamDriverAndConstructorSelections') THEN
    CREATE INDEX "IX_TeamDrivers_UpdatedBy" ON "TeamDrivers" ("UpdatedBy");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251207001544_AddTeamDriverAndConstructorSelections') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20251207001544_AddTeamDriverAndConstructorSelections', '9.0.8');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260111014113_AddTimestampsToUserProfile') THEN
    ALTER TABLE "UserProfiles" ADD "CreatedAt" timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260111014113_AddTimestampsToUserProfile') THEN
    ALTER TABLE "UserProfiles" ADD "UpdatedAt" timestamp with time zone;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260111014113_AddTimestampsToUserProfile') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260111014113_AddTimestampsToUserProfile', '9.0.8');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260112195055_AddLeagueTeamManyToMany') THEN
    CREATE TABLE "LeagueTeams" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "LeagueId" integer NOT NULL,
        "TeamId" integer NOT NULL,
        "JoinedAt" timestamp with time zone NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone,
        "DeletedAt" timestamp with time zone,
        "IsDeleted" boolean NOT NULL,
        "CreatedBy" integer NOT NULL,
        "UpdatedBy" integer,
        "DeletedBy" integer,
        CONSTRAINT "PK_LeagueTeams" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_LeagueTeams_Leagues_LeagueId" FOREIGN KEY ("LeagueId") REFERENCES "Leagues" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_LeagueTeams_Teams_TeamId" FOREIGN KEY ("TeamId") REFERENCES "Teams" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_LeagueTeams_UserProfiles_CreatedBy" FOREIGN KEY ("CreatedBy") REFERENCES "UserProfiles" ("Id") ON DELETE RESTRICT,
        CONSTRAINT "FK_LeagueTeams_UserProfiles_DeletedBy" FOREIGN KEY ("DeletedBy") REFERENCES "UserProfiles" ("Id") ON DELETE RESTRICT,
        CONSTRAINT "FK_LeagueTeams_UserProfiles_UpdatedBy" FOREIGN KEY ("UpdatedBy") REFERENCES "UserProfiles" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260112195055_AddLeagueTeamManyToMany') THEN
    CREATE INDEX "IX_LeagueTeams_CreatedBy" ON "LeagueTeams" ("CreatedBy");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260112195055_AddLeagueTeamManyToMany') THEN
    CREATE INDEX "IX_LeagueTeams_DeletedBy" ON "LeagueTeams" ("DeletedBy");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260112195055_AddLeagueTeamManyToMany') THEN
    CREATE UNIQUE INDEX "IX_LeagueTeams_LeagueId_TeamId" ON "LeagueTeams" ("LeagueId", "TeamId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260112195055_AddLeagueTeamManyToMany') THEN
    CREATE INDEX "IX_LeagueTeams_TeamId" ON "LeagueTeams" ("TeamId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260112195055_AddLeagueTeamManyToMany') THEN
    CREATE INDEX "IX_LeagueTeams_UpdatedBy" ON "LeagueTeams" ("UpdatedBy");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260112195055_AddLeagueTeamManyToMany') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260112195055_AddLeagueTeamManyToMany', '9.0.8');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260121184839_AddLeagueInvite') THEN
    CREATE TABLE "LeagueInvites" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "LeagueId" integer NOT NULL,
        "Token" text,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone,
        "DeletedAt" timestamp with time zone,
        "IsDeleted" boolean NOT NULL,
        "CreatedBy" integer NOT NULL,
        "UpdatedBy" integer,
        "DeletedBy" integer,
        CONSTRAINT "PK_LeagueInvites" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_LeagueInvites_Leagues_LeagueId" FOREIGN KEY ("LeagueId") REFERENCES "Leagues" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_LeagueInvites_UserProfiles_CreatedBy" FOREIGN KEY ("CreatedBy") REFERENCES "UserProfiles" ("Id") ON DELETE RESTRICT,
        CONSTRAINT "FK_LeagueInvites_UserProfiles_DeletedBy" FOREIGN KEY ("DeletedBy") REFERENCES "UserProfiles" ("Id") ON DELETE RESTRICT,
        CONSTRAINT "FK_LeagueInvites_UserProfiles_UpdatedBy" FOREIGN KEY ("UpdatedBy") REFERENCES "UserProfiles" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260121184839_AddLeagueInvite') THEN
    CREATE INDEX "IX_LeagueInvites_CreatedBy" ON "LeagueInvites" ("CreatedBy");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260121184839_AddLeagueInvite') THEN
    CREATE INDEX "IX_LeagueInvites_DeletedBy" ON "LeagueInvites" ("DeletedBy");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260121184839_AddLeagueInvite') THEN
    CREATE UNIQUE INDEX "IX_LeagueInvites_LeagueId" ON "LeagueInvites" ("LeagueId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260121184839_AddLeagueInvite') THEN
    CREATE UNIQUE INDEX "IX_LeagueInvites_Token" ON "LeagueInvites" ("Token");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260121184839_AddLeagueInvite') THEN
    CREATE INDEX "IX_LeagueInvites_UpdatedBy" ON "LeagueInvites" ("UpdatedBy");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260121184839_AddLeagueInvite') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260121184839_AddLeagueInvite', '9.0.8');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260122023115_MakeTokenRequired') THEN
    UPDATE "LeagueInvites" SET "Token" = '' WHERE "Token" IS NULL;
    ALTER TABLE "LeagueInvites" ALTER COLUMN "Token" SET NOT NULL;
    ALTER TABLE "LeagueInvites" ALTER COLUMN "Token" SET DEFAULT '';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260122023115_MakeTokenRequired') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260122023115_MakeTokenRequired', '9.0.8');
    END IF;
END $EF$;
COMMIT;

