-- Standalone price UPDATE script — run manually against any environment to set prices without a deploy.
-- 2026 prices calculated from 2025 season averages via round_to_100K(262,000 × season_avg).
-- Generated by scripts/fetch-sportsdeck-prices.py

-- Driver prices
UPDATE "Drivers" SET "Price" = 7700000  WHERE "Abbreviation" = 'ALB';
UPDATE "Drivers" SET "Price" = 5300000  WHERE "Abbreviation" = 'ALO';
UPDATE "Drivers" SET "Price" = 11700000 WHERE "Abbreviation" = 'ANT';
UPDATE "Drivers" SET "Price" = 6500000  WHERE "Abbreviation" = 'BEA';
UPDATE "Drivers" SET "Price" = 3100000  WHERE "Abbreviation" = 'BOR';
UPDATE "Drivers" SET "Price" = 3000000  WHERE "Abbreviation" = 'BOT';
UPDATE "Drivers" SET "Price" = 3000000  WHERE "Abbreviation" = 'COL';
UPDATE "Drivers" SET "Price" = 3000000  WHERE "Abbreviation" = 'DOO';
UPDATE "Drivers" SET "Price" = 3200000  WHERE "Abbreviation" = 'GAS';
UPDATE "Drivers" SET "Price" = 5700000  WHERE "Abbreviation" = 'HAD';
UPDATE "Drivers" SET "Price" = 11800000 WHERE "Abbreviation" = 'HAM';
UPDATE "Drivers" SET "Price" = 6800000  WHERE "Abbreviation" = 'HUL';
UPDATE "Drivers" SET "Price" = 4400000  WHERE "Abbreviation" = 'LAW';
UPDATE "Drivers" SET "Price" = 16500000 WHERE "Abbreviation" = 'LEC';
UPDATE "Drivers" SET "Price" = 3000000  WHERE "Abbreviation" = 'LIN';
UPDATE "Drivers" SET "Price" = 28200000 WHERE "Abbreviation" = 'NOR';
UPDATE "Drivers" SET "Price" = 5500000  WHERE "Abbreviation" = 'OCO';
UPDATE "Drivers" SET "Price" = 3000000  WHERE "Abbreviation" = 'PER';
UPDATE "Drivers" SET "Price" = 27000000 WHERE "Abbreviation" = 'PIA';
UPDATE "Drivers" SET "Price" = 20600000 WHERE "Abbreviation" = 'RUS';
UPDATE "Drivers" SET "Price" = 6100000  WHERE "Abbreviation" = 'SAI';
UPDATE "Drivers" SET "Price" = 5000000  WHERE "Abbreviation" = 'STR';
UPDATE "Drivers" SET "Price" = 5000000  WHERE "Abbreviation" = 'TSU';
UPDATE "Drivers" SET "Price" = 27400000 WHERE "Abbreviation" = 'VER';

-- Constructor prices
UPDATE "Constructors" SET "Price" = 4400000  WHERE "Abbreviation" = 'ALP';
UPDATE "Constructors" SET "Price" = 7900000  WHERE "Abbreviation" = 'AMR';
UPDATE "Constructors" SET "Price" = 8100000  WHERE "Abbreviation" = 'AUD';
UPDATE "Constructors" SET "Price" = 3000000  WHERE "Abbreviation" = 'CAD';
UPDATE "Constructors" SET "Price" = 19000000 WHERE "Abbreviation" = 'FER';
UPDATE "Constructors" SET "Price" = 10100000 WHERE "Abbreviation" = 'HAA';
UPDATE "Constructors" SET "Price" = 34900000 WHERE "Abbreviation" = 'MCL';
UPDATE "Constructors" SET "Price" = 21200000 WHERE "Abbreviation" = 'MER';
UPDATE "Constructors" SET "Price" = 21600000 WHERE "Abbreviation" = 'RBR';
UPDATE "Constructors" SET "Price" = 7000000  WHERE "Abbreviation" = 'RBS';
UPDATE "Constructors" SET "Price" = 10300000 WHERE "Abbreviation" = 'WIL';
